p8105_hw1_yl4610
================
Yuxin Liu
2022-09-18

install.packages(“palmerpenguins”) in console

\#question1

``` r
# load the tidyverse library 
library(tidyverse)
# load the penguins dataset
data("penguins", package = "palmerpenguins")
# for values of important variable; short descriptions are written below 
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

The data in this dataset, including names / values of important variable
is: species, island, bill_length_mm, bill_depth_mm, flipper_length_mm,
body_mass_g, sex, year

species: Adelie(152); Chinstrap(68); Gentoo(124). island: Biscoe(168);
Dream(124); Torgersen(52). sex: female(165); male(168); NA’s(11).

bill_length_mm ranges from 32.10 mm to 59.60 mm. bill_depth_mm ranges
from 13.10 mm to 21.50 mm. flipper_length_mm ranges from 172 mm to 231
mm. body_mass_g ranges from 2700 g to 6300 g. year ranges from 2007 to
2009.

The size of the dataset (using nrow and ncol): is 344 rows and 8
columns.

The mean flipper length is: 200.9152047mm

``` r
# make a scatterplot of flipper_length_mm (y) vs bill_length_mm (x)
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point() 
```

![](p8105_hw1_yl4610_files/figure-gfm/unnamed-chunk-2-1.png)<!-- -->

``` r
# export scatterplot and save it as pdf 
ggsave("scatter_plot.pdf")
```

\#question2

``` r
# create a data frame
ans2 = tibble(
  norm_samp = rnorm(10),
  norm_samp_pos = norm_samp > 0,
  char_vec =  letters[1:10],
  fac_vec = factor(c("level1", "level1", "level1","level2","level2", "level2", "level3","level3","level3", "level3"), levels = c("level1", "level2", "level3")),
)
# take the mean of each variable 
mean(pull(ans2, norm_samp))
```

    ## [1] 0.4080844

``` r
mean(pull(ans2, norm_samp_pos))
```

    ## [1] 0.7

``` r
mean(pull(ans2, char_vec))
```

    ## [1] NA

``` r
mean(pull(ans2, fac_vec))
```

    ## [1] NA

We cannot compute means of character vector and factor vector (outcomes
are NA for both types of variables). We only can compute mean of numeric
or logical factor. The means for numeric or logical factor are numbers.

``` r
# convert variables
as.numeric(pull(ans2, norm_samp_pos))
as.numeric(pull(ans2, char_vec))
as.numeric(pull(ans2, fac_vec))
```

When the logical vector is true, value becomes 1; when the logical
vector is false, value becomes 0; Logical vectors are converted to
numbers based on elements of the sample are greater than 0. The
character vectors become NA. The factor vectors become 1,2,3, according
to their levels. Therefore, we can take the means of logical and factor
characters after conversions. Yes, it helps explain what happens when I
try to take the mean.
